#include "ConvertCS.h"

#define IMPLEMENT_PERMUTATION(InputComponents, OutputComponents) typedef TConvertCS<InputComponents, OutputComponents> TConvertCS##InputComponents##OutputComponents##;   \
    IMPLEMENT_SHADER_TYPE(template<> SHADERSPLUS_API, TConvertCS##InputComponents##OutputComponents##, TEXT("/Plugin/ShadersPlus/Private/ConvertCS.usf"), TEXT("MainCS"), SF_Compute);

IMPLEMENT_PERMUTATION(1, 1)
IMPLEMENT_PERMUTATION(1, 2)
IMPLEMENT_PERMUTATION(1, 3)
IMPLEMENT_PERMUTATION(1, 4)

IMPLEMENT_PERMUTATION(2, 1)
IMPLEMENT_PERMUTATION(2, 2)
IMPLEMENT_PERMUTATION(2, 3)
IMPLEMENT_PERMUTATION(2, 4)

IMPLEMENT_PERMUTATION(3, 1)
IMPLEMENT_PERMUTATION(3, 2)
IMPLEMENT_PERMUTATION(3, 3)
IMPLEMENT_PERMUTATION(3, 4)

IMPLEMENT_PERMUTATION(4, 1)
IMPLEMENT_PERMUTATION(4, 2)
IMPLEMENT_PERMUTATION(4, 3)
IMPLEMENT_PERMUTATION(4, 4)

#undef IMPLEMENT_PERMUTATION