#include "ConvertCS.h"

#define IMPLEMENT_CONVERTCS(InputComponents, OutputComponents) typedef TConvertCS<InputComponents, OutputComponents> TConvertCS##InputComponents##OutputComponents##;   \
    IMPLEMENT_SHADER_TYPE(template<> SHADERSPLUS_API, TConvertCS##InputComponents##OutputComponents##, TEXT("/Plugin/ShadersPlus/Private/ConvertCS.usf"), TEXT("MainCS"), SF_Compute);

IMPLEMENT_CONVERTCS(1, 1)
IMPLEMENT_CONVERTCS(1, 2)
IMPLEMENT_CONVERTCS(1, 3)
IMPLEMENT_CONVERTCS(1, 4)

IMPLEMENT_CONVERTCS(2, 1)
IMPLEMENT_CONVERTCS(2, 2)
IMPLEMENT_CONVERTCS(2, 3)
IMPLEMENT_CONVERTCS(2, 4)

IMPLEMENT_CONVERTCS(3, 1)
IMPLEMENT_CONVERTCS(3, 2)
IMPLEMENT_CONVERTCS(3, 3)
IMPLEMENT_CONVERTCS(3, 4)

IMPLEMENT_CONVERTCS(4, 1)
IMPLEMENT_CONVERTCS(4, 2)
IMPLEMENT_CONVERTCS(4, 3)
IMPLEMENT_CONVERTCS(4, 4)

#undef IMPLEMENT_CONVERTCS